apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v1
  annotations: {}
  labels:
    app: ratings
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
        - name: ratings
          image: docker.io/istio/examples-bookinfo-ratings-v1:1.20.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
