apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: true
    accessLogFile: /dev/stdout
    accessLogFormat: |
      {"start_time":"%START_TIME%","method":"%REQ(:METHOD)%","path":"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%","protocol":"%PROTOCOL%","response_code":"%RESPONSE_CODE%","duration":"%DURATION%","upstream_host":"%UPSTREAM_HOST%"}
    defaultConfig:
      proxyMetadata:
        ISTIO_META_TRACING_PROVIDER: "otel-tracing"
        ISTIO_META_ENABLE_ENVOY_ACCESS_LOGS: "true"
        ISTIO_META_ENABLE_ENVOY_ACCESS_LOG_SERVICE: "true"
      tracing:
        sampling: 100
    extensionProviders:
      - name: otel-tracing
        opentelemetry:
          port: 4317
          service: jaeger-collector.infra-dev.svc.cluster.local
          resource_detectors:
            environment: {}
