labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: kiali
      app.kubernetes.io/instance: kiali
      version: "v2.8.0"
      app.kubernetes.io/version: "v2.8.0"
      app.kubernetes.io/part-of: "kiali"
# https://kiali.io/

resources:
  - service-account.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
