apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
    - name: http-jaeger-collector
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: grpc-jaeger-collector
      port: 14250
      targetPort: 14250
      protocol: TCP
    - port: 9411
      targetPort: 9411
      name: http-zipkin
    - port: 4317
      name: grpc-otel
    - port: 4318
      name: http-otel
  selector:
    app: jaeger
