- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      cpu: "500m"
      memory: "150Mi"
    limits:
      cpu: "500m"
      memory: "150Mi"

- op: add
  path: /spec/template/spec/containers/0/startupProbe
  value:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 40
    failureThreshold: 5
    periodSeconds: 8

- op: add
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 0
    timeoutSeconds: 5
    failureThreshold: 5

- op: add
  path: /spec/template/spec/containers/0/readinessProbe
  value:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10
